### ISSUE TITLE
정말로 감사드립니다.

### ISSUE THREAD

**Issue by Leowolf93** [jubin-park/RPGMakerHook#1]
대단히 감사드립니다, 대가님의 hook 라이브러리에 정말 감사드립니다! 현재 제가 하나 궁금한 점이 있습니다, 게임 내의 텍스트 정보를 직접 hook하여 클립보드로 전송하는 것이 가능할까요? 몇몇 게임을 정말로 해보고 싶은데, 패치가 없어서요. 하지만 일부 번역기는 클립보드 내의 텍스트를 직접 읽어서 번역할 수 있습니다, 이것이 가능한지 궁금합니다.
정말로 감사드립니다.

**Comment by jubin-park** [comment]
@Leowolf93 님 안녕하세요. 답장이 늦어 죄송합니다.

문의주신 질문은 본 프로젝트과 관련이 없어보입니다.

실시간으로 게임에서 출력되는 텍스트를 번역하고자 하시는 것으로 보이는데요!
[알만툴 실시간 번역](https://www.google.com/search?q=%EC%95%8C%EB%A7%8C%ED%88%B4+%EC%8B%A4%EC%8B%9C%EA%B0%84+%EB%B2%88%EC%97%AD) 키워드로 검색하여 관련 내용을 찾아보시길 바랍니다.

감사합니다.
